CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR(15) NOT NULL UNIQUE,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('M', 'F')),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(50),
    HOBBY VARCHAR2(50),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
    
    
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'admin', '1234', '관리자', 'M', 45, 'admin@naver.com', 
        '01022334455', '서울시 양천구', '잠자기', '2021/1/24');
        
INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'ad', 'pass', '홍길녀', 'F', 23, NULL, 
        '0102233335', NULL, '독서', '2021/2/3');        
        
        COMMIT;